server {
    listen 80;
    server_name gladdenglobalnetwork.com www.gladdenglobalnetwork.com;
    root /root/ggn-site;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
